id = "snovalang"
name = "Snovalang"
version = "0.1.0"
schema_version = 1
authors = ["Aggitech Team <dev@aggitech.com>"]
description = "Snovalang language support and LSP integration for Zed editor"
repository = "https://github.com/supernovalang/editor-extensions"

[grammars.snovalang]
repository = "https://github.com/supernovalang/editor-extensions"
path = "zed/tree-sitter-snovalang"
rev = "9ffdc254253d1a7245f0a78ea3dddc39887da1d4"

[grammars.snovalang_manifest]
repository = "https://github.com/supernovalang/editor-extensions"
path = "zed/tree-sitter-snovalang-manifest"
rev = "9ffdc254253d1a7245f0a78ea3dddc39887da1d4"

[language_servers.snova_lsp]
name = "snova-lsp"
languages = ["Snovalang", "Snovalang Manifest"]
